# Generated by Django 6.0.5 on 2026-05-25 11:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['last_used', 'use_count'],
            },
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating content'), ('ASSEMBLING', 'Assembling video'), ('UPLOADING', 'Uploading to YouTube'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('script', models.TextField(blank=True)),
                ('audio_path', models.CharField(blank=True, max_length=500)),
                ('video_path', models.CharField(blank=True, max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('youtube_video_url', models.URLField(blank=True)),
                ('error_stage', models.CharField(blank=True, max_length=50)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video job',
                'verbose_name_plural': 'Video jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
