# Generated by Django 6.0.5 on 2026-05-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
