# Generated by Django 6.0.5 on 2026-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videojob_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='keywords',
        ),
        migrations.AddField(
            model_name='videojob',
            name='scenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
