# Generated by Django 6.0.5 on 2026-05-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_videojob_keywords_videojob_scenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
